### ISSUE TITLE
No module named "usb" error

### ISSUE THREAD

**Issue by GrinFactor** [MAVProxyUser/CIAJeepDoors#13]
Hi there, 

I'm trying to use this with my Mavic 3 and I'm getting the following error. 
-----------------------------------------------------------------------------------------------
d:\dji-firmware-tools-master>python CIAJeepDoors.py --bulk --disable
CIA Jeep Doors
DJI DroneID adjustment tool v1.3
======================================
this software is based on the work of the DJI OG's
it is free software and should never be sold
======================================
greetings from Bin4ry
Traceback (most recent call last):
  File "d:\dji-firmware-tools-master\CIAJeepDoors.py", line 260, in <module>
    main()
  File "d:\dji-firmware-tools-master\CIAJeepDoors.py", line 222, in main
    ser = open_usb(po)
  File "d:\dji-firmware-tools-master\.\comm_serialtalk.py", line 148, in open_usb
    import usb.core
ModuleNotFoundError: No module named 'usb'
------------------------------------------------------------------------------------------------

I've already updated with the following commands:
python -m pip install python-dev-tools
python -m pip install --upgrade pip
python -m pip install pyserial

but i'm still getting the same error. 

The mavic 3 is detected by the pc and dji assistant 2 for consumer drone.

**Comment by Newegz** [comment]
Did you try 
python -m pip install usb 
and 
python -m pip install pyusb?

**Comment by GrinFactor** [comment]
yes, I did. 

I've found that it works on my Air2S but not on my Mavic 3 - I've redownloaded the 1.3 file and tried again. All seems to be working but the Mavic 3 is not detected using the Bulk option. Might be that the firmware has been updated to a point where the mod does not work anymore.

**Comment by psxbxr** [comment]
Try flashing your current stock firmware. Also if on Windows 10, disable driver signature enforcement (start > shift click restart > troubleshoot > advanced options > startup settings > #7 Key) before installing DJI assistant and its drivers. Then go to device manager and change the driver the usb port uses from standard to DJI's.

**Comment by aanestaa** [comment]
Hi, l have same problem do you alreadu solved it?
